### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by Ajaxy** [mdn/voice-change-o-matic#1]
Hi! App seems to not work on iPhone and iPad. Only info popup is shown at start. Here is the screenshot:

![](http://chatik.ajaxy.ru/uploads/webaudio.jpg)

**Comment by Ajaxy** [comment]
Cloned and removed popup. Still no effect. It doesn't prompt for microphone access.

**Comment by balaurzor** [comment]
getUserMedia is not supported on Safari or iOs http://caniuse.com/#search=getUserMedia

**Comment by Ajaxy** [comment]
Maybe there are some workarounds or polyfills to make it work on iOS? Thank you.

**Comment by chrisdavidmills** [comment]
This was a while ago (sorry for not noticing this issue until now!) Is this stuff more supported yet?
