### ISSUE TITLE
Please turn on HTTPS for the app site

### ISSUE THREAD

**Issue by Kitanga** [mdn/voice-change-o-matic#10]
The app doesn't work in HTTP. There's a warning that pops up in the console:

![screenshot 26](https://user-images.githubusercontent.com/14119482/29494975-16dd8f68-85be-11e7-8aa3-cbfe067b2ffc.png)

**Comment by chrisdavidmills** [comment]
I've just checked, and the example is working OK, as long as you use the HTTPS protocol to access the demo (GitHub supports both). I accessed it in Chrome using

https://mdn.github.io/voice-change-o-matic/

And it seemed to work OK, without the error you cited.
