### ISSUE TITLE
The live demo does not work

### ISSUE THREAD

**Issue by cmartinez84** [mdn/voice-change-o-matic#11]
console: 
 getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
(anonymous) @ app.js:94
app.js:117 The following gUM error occured: [object NavigatorUserMediaError]

**Comment by chrisdavidmills** [comment]
Tested in Chrome; this seems to work fine now.
