### ISSUE TITLE
Analysis should be applied after filters

### ISSUE THREAD

**Issue by derpmarine168** [mdn/voice-change-o-matic#17]
the visualisation is applied before filters.
set up the voice-change-O-matic like this:
![image](https://user-images.githubusercontent.com/28905212/48664533-d3d96080-ea97-11e8-8332-3540f49ca34f.png)
the reverb is not visualiesd.
your web audio api is set up like this according to firefox web audio api.
![image](https://user-images.githubusercontent.com/28905212/48664523-c0c69080-ea97-11e8-8fed-a894f5a00a2b.png)
it should have Analyser and WaveShaper last.

**Comment by chrisdavidmills** [comment]
This is an extremely good point; thanks for reporting. I've now put the analyser last, and now you see accurate visualizations of the audio with the filters added. I can't believe this was broken for so long ;-)
