### ISSUE TITLE
Mute button doesn't work on voice-change-o-matic

### ISSUE THREAD

**Issue by jon-mellon** [mdn/voice-change-o-matic#22]
Pressing the mute and umute does nothing to the sound on my browser. 
Windows 10
Chrome: Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by jon-mellon** [comment]
I've also tried running it on firefox and the mute button doesn't appear to work there either. The other voice settings do noticeably change the sound on both browsers.

**Comment by chrisdavidmills** [comment]
Hi @jon-mellon , thanks for reporting this!

The click handler we had added that allows it to work now that gUM can only be used in response to a user gesture broke the mute functionality. I've fixed it by removing the event handler once `init()` has been run. I also made the mute code simpler — just setting `gainNode.value` to 0, then 1, when mute is toggled on and off.

See https://github.com/mdn/voice-change-o-matic/commit/03186f47dcdde839a0a3ce21737f0c6bd1a38159
