### ISSUE TITLE
Suggestion to enforce HTTPS

### ISSUE THREAD

**Issue by SKaralius** [mdn/voice-change-o-matic#23]
Hi,

I noticed this issue, because [this page](https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/frequencyBinCount) links to http for voice-o-matic. Because navigator.mediaDevices.getUserMedia() will throw a NotAllowedError if the website is loaded over http, the app will not work in most, if not all, browsers.

I would suggest to check Enforce HTTPS under Github page settings to make sure that this error would not occur no matter what is linked.

**Comment by chrisdavidmills** [comment]
Thanks for the suggestion @SKaralius . I've fixed the link on the page, but I've also checked the "Enforce HTTPS" option for this repo!
