### ISSUE TITLE
Sinwave visualizer is actually just drawing smaller frequency bars

### ISSUE THREAD

**Issue by Ajedi32** [mdn/voice-change-o-matic#3]
Thanks to function hoisting, you could literally remove [this function](https://github.com/mdn/voice-change-o-matic/blob/gh-pages/scripts/app.js#L140-L173) and your code would still behave the same way. As-is, both the sine wave and frequency settings for this visualizer do basically the same thing.

**Comment by Ajedi32** [comment]
Ah, looks like I'm not the first to notice. This is fixed by #2 (please just merge that already)...

**Comment by chrisdavidmills** [comment]
I merged that PR, so this is fixed now. My future code will be written better than this ;-)
