### ISSUE TITLE
Question about Web Audio API

### ISSUE THREAD

**Issue by zlelik** [mdn/voice-change-o-matic#4]
Could you please add stop button to this example?
There is mute button, but it is just change some filter parameter (basically just put gain to 0). How to completely stop sound processing?

**Comment by chrisdavidmills** [comment]
This example might help you:

https://github.com/mdn/audiocontext-states

The new states were added more recently, way after I wrote the voice changer demo

**Comment by zlelik** [comment]
Thank for the link. But it does not work in this case.  audioCtx.close() does not really do anything in this example, which use navigator.mediaDevices.getUserMedia and etc. audioCtx.close() works only if we use simple audioCtx like this

AudioContext = window.AudioContext || window.webkitAudioContext;
audioCtx = new AudioContext();

but if I use navigator.mediaDevices.getUserMedia or navigator.getUserMedia, audioCtx.close() does not do anything :(

I just want to implement stop button in my example like yours voice-change-o-matic.
