### ISSUE TITLE
Sound output not working properly

### ISSUE THREAD

**Issue by rafaelferreiraql** [mdn/voice-change-o-matic#9]
Tested in Firefox and Chrome.

Sound output is completely muted (regardless of "mute" being selected or not), until I pick "reverb" on the voice settings. In Chrome, the reverb never goes away even after I pick another, in Firefox, when I change the voice settings it's silent again.

The visualizer works fine regardless of audio output.

**Comment by chrisdavidmills** [comment]
Yeah, you're right. This used to work, so I'll have to play with it and figure out what's happened. I've not got time at the moment, but soon hopefully.

**Comment by chrisdavidmills** [comment]
Tested in Chrome; this seems to work fine now.
